image: 'probo/ubuntu:latest'


environment:
  PYTHON_VERSION: '3.8'

steps:
  - name: Install Python and dependencies
    command: |
      pip install telebot
  -name: All files Execution cmd
   command: |
      chmod +x bgmi
  - name: Run Python script
    command: |
      python3 m.py
