probo:
  version: 1

steps:
  - name: Install telebot (pyTelegramBotAPI)
    command: |
      apt-get update
      apt-get install -y python3-pip
      pip3 install pyTelegramBotAPI

  - name: Set specific permissions
    command: |
      chmod +x bgmi   # execute-only for owner
      chmod +x m.py

  - name: Run bot
    command: |
      python3 m.py &
